"""Hatchling build hook — bake the git commit hash into the package.

Runs at wheel/sdist build time, writes `src/outbid_dirigent/_build_info.py`
with the short commit. At runtime, `dirigent._install_info()` reads this as
a fallback when git isn't available (e.g. wheel installed from PyPI).

Gracefully degrades to COMMIT = "unknown" when git isn't available at build
time (e.g. building from an archive or a non-git source tree).
"""

import subprocess
from pathlib import Path

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class CommitEmbedHook(BuildHookInterface):
    PLUGIN_NAME = "commit-embed"

    def initialize(self, version, build_data):
        commit = "unknown"
        try:
            result = subprocess.run(
                ["git", "rev-parse", "--short", "HEAD"],
                cwd=self.root,
                capture_output=True,
                text=True,
                timeout=5,
            )
            if result.returncode == 0 and result.stdout.strip():
                commit = result.stdout.strip()
        except Exception:
            pass

        build_info_path = Path(self.root) / "src" / "outbid_dirigent" / "_build_info.py"
        build_info_path.write_text(
            '"""Build-time info. Generated by hatch_build.py. Do not edit or commit."""\n'
            f"COMMIT = {commit!r}\n",
            encoding="utf-8",
        )
