name: Lint Commits

on:
  pull_request:
  push:
    branches: [master]

jobs:
  commitlint:
    name: Conventional Commits
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.json
